
DROP TABLE IF EXISTS `care_encounter_event_signaller`;
CREATE TABLE `care_encounter_event_signaller` (
  `encounter_nr` varchar(12) NOT NULL DEFAULT '0',
  `yellow` tinyint(1) NOT NULL DEFAULT '0',
  `black` tinyint(1) NOT NULL DEFAULT '0',
  `blue_pale` tinyint(1) NOT NULL DEFAULT '0',
  `brown` tinyint(1) NOT NULL DEFAULT '0',
  `pink` tinyint(1) NOT NULL DEFAULT '0',
  `yellow_pale` tinyint(1) NOT NULL DEFAULT '0',
  `red` tinyint(1) NOT NULL DEFAULT '0',
  `green_pale` tinyint(1) NOT NULL DEFAULT '0',
  `violet` tinyint(1) NOT NULL DEFAULT '0',
  `blue` tinyint(1) NOT NULL DEFAULT '0',
  `biege` tinyint(1) NOT NULL DEFAULT '0',
  `orange` tinyint(1) NOT NULL DEFAULT '0',
  `green_1` tinyint(1) NOT NULL DEFAULT '0',
  `green_2` tinyint(1) NOT NULL DEFAULT '0',
  `green_3` tinyint(1) NOT NULL DEFAULT '0',
  `green_4` tinyint(1) NOT NULL DEFAULT '0',
  `green_5` tinyint(1) NOT NULL DEFAULT '0',
  `green_6` tinyint(1) NOT NULL DEFAULT '0',
  `green_7` tinyint(1) NOT NULL DEFAULT '0',
  `rose_1` tinyint(1) NOT NULL DEFAULT '0',
  `rose_2` tinyint(1) NOT NULL DEFAULT '0',
  `rose_3` tinyint(1) NOT NULL DEFAULT '0',
  `rose_4` tinyint(1) NOT NULL DEFAULT '0',
  `rose_5` tinyint(1) NOT NULL DEFAULT '0',
  `rose_6` tinyint(1) NOT NULL DEFAULT '0',
  `rose_7` tinyint(1) NOT NULL DEFAULT '0',
  `rose_8` tinyint(1) NOT NULL DEFAULT '0',
  `rose_9` tinyint(1) NOT NULL DEFAULT '0',
  `rose_10` tinyint(1) NOT NULL DEFAULT '0',
  `rose_11` tinyint(1) NOT NULL DEFAULT '0',
  `rose_12` tinyint(1) NOT NULL DEFAULT '0',
  `rose_13` tinyint(1) NOT NULL DEFAULT '0',
  `rose_14` tinyint(1) NOT NULL DEFAULT '0',
  `rose_15` tinyint(1) NOT NULL DEFAULT '0',
  `rose_16` tinyint(1) NOT NULL DEFAULT '0',
  `rose_17` tinyint(1) NOT NULL DEFAULT '0',
  `rose_18` tinyint(1) NOT NULL DEFAULT '0',
  `rose_19` tinyint(1) NOT NULL DEFAULT '0',
  `rose_20` tinyint(1) NOT NULL DEFAULT '0',
  `rose_21` tinyint(1) NOT NULL DEFAULT '0',
  `rose_22` tinyint(1) NOT NULL DEFAULT '0',
  `rose_23` tinyint(1) NOT NULL DEFAULT '0',
  `rose_24` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`encounter_nr`),
  CONSTRAINT `FK_care_encounter_event_signaller` FOREIGN KEY (`encounter_nr`) REFERENCES `care_encounter` (`encounter_nr`) ON DELETE CASCADE ON UPDATE CASCADE
);
