
DROP TABLE IF EXISTS `care_person`;
CREATE TABLE `care_person` (
  `pid` varchar(12) NOT NULL,
  `date_reg` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `name_first` varchar(60) NOT NULL,
  `name_2` varchar(60) DEFAULT NULL,
  `name_3` varchar(60) DEFAULT NULL,
  `name_middle` varchar(60) DEFAULT NULL,
  `name_last` varchar(60) NOT NULL,
  `suffix` varchar(10) DEFAULT NULL,
  `name_maiden` varchar(60) DEFAULT NULL,
  `name_others` text NOT NULL,
  `title` varchar(25) DEFAULT NULL,
  `date_birth` date NOT NULL DEFAULT '0000-00-00',
  `birth_time` time DEFAULT '00:00:00',
  `place_birth` varchar(60) DEFAULT NULL,
  `blood_group` char(2) NOT NULL,
  `addr_str` varchar(60) NOT NULL,
  `addr_str_nr` varchar(10) NOT NULL,
  `addr_zip` varchar(15) NOT NULL,
  `addr_citytown_nr` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `addr_is_valid` tinyint(1) NOT NULL DEFAULT '0',
  `street_name` varchar(100) DEFAULT NULL,
  `brgy_nr` int(11) unsigned DEFAULT NULL,
  `mun_nr` int(11) unsigned NOT NULL,
  `citizenship` varchar(5) DEFAULT 'PH',
  `occupation` varchar(25) DEFAULT '1',
  `employer` varchar(50) DEFAULT NULL,
  `phone_1_code` varchar(15) DEFAULT '0',
  `phone_1_nr` varchar(35) DEFAULT NULL,
  `phone_2_code` varchar(15) DEFAULT '0',
  `phone_2_nr` varchar(35) DEFAULT NULL,
  `cellphone_1_nr` varchar(35) DEFAULT NULL,
  `cellphone_2_nr` varchar(35) DEFAULT NULL,
  `fax` varchar(35) DEFAULT NULL,
  `email` varchar(60) DEFAULT NULL,
  `civil_status` varchar(35) NOT NULL,
  `sex` char(1) NOT NULL,
  `photo` blob,
  `photo_filename` varchar(60) NOT NULL,
  `fpimage_filename` varchar(60) DEFAULT NULL,
  `ethnic_orig` mediumint(8) unsigned DEFAULT NULL,
  `org_id` varchar(60) DEFAULT NULL,
  `sss_nr` varchar(60) DEFAULT NULL,
  `nat_id_nr` varchar(60) DEFAULT NULL,
  `religion` varchar(125) DEFAULT '1',
  `mother_pid` int(11) unsigned NOT NULL DEFAULT '0',
  `mother_fname` varchar(50) DEFAULT NULL,
  `mother_maidenname` varchar(50) DEFAULT NULL,
  `mother_mname` varchar(50) DEFAULT NULL,
  `mother_lname` varchar(50) DEFAULT NULL,
  `father_pid` int(11) unsigned NOT NULL DEFAULT '0',
  `father_fname` varchar(50) DEFAULT NULL,
  `father_mname` varchar(50) DEFAULT NULL,
  `father_lname` varchar(50) DEFAULT NULL,
  `spouse_name` varchar(50) DEFAULT NULL,
  `guardian_name` varchar(50) DEFAULT NULL,
  `contact_person` varchar(255) DEFAULT NULL,
  `contact_pid` int(11) unsigned NOT NULL DEFAULT '0',
  `contact_relation` varchar(25) DEFAULT '0',
  `death_date` date NOT NULL DEFAULT '0000-00-00',
  `death_time` time DEFAULT '00:00:00',
  `death_encounter_nr` int(10) unsigned NOT NULL DEFAULT '0',
  `death_cause` tinytext,
  `death_cause_code` varchar(15) DEFAULT NULL,
  `date_update` datetime DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `history` text NOT NULL,
  `modify_id` varchar(35) NOT NULL,
  `modify_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL,
  `create_time` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `fromtemp` tinyint(1) DEFAULT '0',
  `admitted_baby` tinyint(1) DEFAULT '0',
  `senior_ID` varchar(25) DEFAULT NULL,
  `veteran_ID` varchar(25) DEFAULT NULL,
  `is_indigent` int(1) DEFAULT '0',
  `DOH_ID` varbinary(25) DEFAULT NULL,
  `age` int(5) DEFAULT NULL,
  `name_search` varchar(150) NOT NULL,
  `soundex_namelast` varchar(150) NOT NULL,
  `soundex_namefirst` varchar(150) NOT NULL,
  `is_temp_bdate` tinyint(1) DEFAULT '0',
  `contact_no` varchar(25) NOT NULL,
  PRIMARY KEY (`pid`),
  KEY `name_last` (`name_last`),
  KEY `name_first` (`name_first`),
  KEY `date_reg` (`date_reg`),
  KEY `date_birth` (`date_birth`),
  KEY `FK_care_person_brgy` (`brgy_nr`),
  KEY `FK_care_person_muncity` (`mun_nr`),
  KEY `deathdate_index` (`death_date`),
  KEY `name_index` (`name_last`,`name_first`,`name_middle`),
  KEY `namelast_namefirst_index` (`name_last`,`name_first`),
  KEY `namesearch_index` (`name_search`),
  KEY `soundexnamelast_index` (`soundex_namelast`),
  KEY `soundexnamefirst_index` (`soundex_namefirst`),
  KEY `mun_code` (`mun_nr`),
  KEY `brgy_code` (`brgy_nr`),
  CONSTRAINT `FK_care_person_brgy` FOREIGN KEY (`brgy_nr`) REFERENCES `seg_barangays` (`brgy_nr`) ON UPDATE CASCADE,
  CONSTRAINT `FK_care_person_muncity` FOREIGN KEY (`mun_nr`) REFERENCES `seg_municity` (`mun_nr`) ON UPDATE CASCADE
);
