
DROP TABLE IF EXISTS `care_test_request_blood`;
CREATE TABLE `care_test_request_blood` (
  `batch_nr` int(11) NOT NULL,
  `encounter_nr` int(11) unsigned NOT NULL DEFAULT '0',
  `dept_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `blood_group` varchar(10) NOT NULL DEFAULT '',
  `rh_factor` varchar(10) NOT NULL DEFAULT '',
  `kell` varchar(10) NOT NULL DEFAULT '',
  `date_protoc_nr` varchar(45) NOT NULL DEFAULT '',
  `pure_blood` varchar(15) NOT NULL DEFAULT '',
  `red_blood` varchar(15) NOT NULL DEFAULT '',
  `leukoless_blood` varchar(15) NOT NULL DEFAULT '',
  `washed_blood` varchar(15) NOT NULL DEFAULT '',
  `prp_blood` varchar(15) NOT NULL DEFAULT '',
  `thrombo_con` varchar(15) NOT NULL DEFAULT '',
  `ffp_plasma` varchar(15) NOT NULL DEFAULT '',
  `transfusion_dev` varchar(15) NOT NULL DEFAULT '',
  `match_sample` tinyint(4) NOT NULL DEFAULT '0',
  `transfusion_date` date NOT NULL DEFAULT '0000-00-00',
  `diagnosis` tinytext NOT NULL,
  `notes` tinytext NOT NULL,
  `send_date` date NOT NULL DEFAULT '0000-00-00',
  `doctor` varchar(35) NOT NULL DEFAULT '',
  `phone_nr` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(10) NOT NULL DEFAULT '',
  `blood_pb` tinytext NOT NULL,
  `blood_rb` tinytext NOT NULL,
  `blood_llrb` tinytext NOT NULL,
  `blood_wrb` tinytext NOT NULL,
  `blood_prp` tinyblob NOT NULL,
  `blood_tc` tinytext NOT NULL,
  `blood_ffp` tinytext NOT NULL,
  `b_group_count` mediumint(9) NOT NULL DEFAULT '0',
  `b_group_price` float(10,2) NOT NULL DEFAULT '0.00',
  `a_subgroup_count` mediumint(9) NOT NULL DEFAULT '0',
  `a_subgroup_price` float(10,2) NOT NULL DEFAULT '0.00',
  `extra_factors_count` mediumint(9) NOT NULL DEFAULT '0',
  `extra_factors_price` float(10,2) NOT NULL DEFAULT '0.00',
  `coombs_count` mediumint(9) NOT NULL DEFAULT '0',
  `coombs_price` float(10,2) NOT NULL DEFAULT '0.00',
  `ab_test_count` mediumint(9) NOT NULL DEFAULT '0',
  `ab_test_price` float(10,2) NOT NULL DEFAULT '0.00',
  `crosstest_count` mediumint(9) NOT NULL DEFAULT '0',
  `crosstest_price` float(10,2) NOT NULL DEFAULT '0.00',
  `ab_diff_count` mediumint(9) NOT NULL DEFAULT '0',
  `ab_diff_price` float(10,2) NOT NULL DEFAULT '0.00',
  `x_test_1_code` mediumint(9) NOT NULL DEFAULT '0',
  `x_test_1_name` varchar(35) NOT NULL DEFAULT '',
  `x_test_1_count` mediumint(9) NOT NULL DEFAULT '0',
  `x_test_1_price` float(10,2) NOT NULL DEFAULT '0.00',
  `x_test_2_code` mediumint(9) NOT NULL DEFAULT '0',
  `x_test_2_name` varchar(35) NOT NULL DEFAULT '',
  `x_test_2_count` mediumint(9) NOT NULL DEFAULT '0',
  `x_test_2_price` float(10,2) NOT NULL DEFAULT '0.00',
  `x_test_3_code` mediumint(9) NOT NULL DEFAULT '0',
  `x_test_3_name` varchar(35) NOT NULL DEFAULT '',
  `x_test_3_count` mediumint(9) NOT NULL DEFAULT '0',
  `x_test_3_price` float(10,2) NOT NULL DEFAULT '0.00',
  `lab_stamp` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `release_via` varchar(20) NOT NULL DEFAULT '',
  `receipt_ack` varchar(20) NOT NULL DEFAULT '',
  `mainlog_nr` varchar(7) NOT NULL DEFAULT '',
  `lab_nr` varchar(7) NOT NULL DEFAULT '',
  `mainlog_date` date NOT NULL DEFAULT '0000-00-00',
  `lab_date` date NOT NULL DEFAULT '0000-00-00',
  `mainlog_sign` varchar(20) NOT NULL DEFAULT '',
  `lab_sign` varchar(20) NOT NULL DEFAULT '',
  `history` text,
  `modify_id` varchar(35) NOT NULL DEFAULT '',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`batch_nr`),
  KEY `send_date` (`send_date`)
);
