
DROP TABLE IF EXISTS `care_test_request_patho`;
CREATE TABLE `care_test_request_patho` (
  `batch_nr` int(11) unsigned NOT NULL,
  `encounter_nr` int(11) unsigned NOT NULL DEFAULT '0',
  `dept_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `quick_cut` tinyint(4) NOT NULL DEFAULT '0',
  `qc_phone` varchar(40) NOT NULL DEFAULT '',
  `quick_diagnosis` tinyint(4) NOT NULL DEFAULT '0',
  `qd_phone` varchar(40) NOT NULL DEFAULT '',
  `material_type` varchar(25) NOT NULL DEFAULT '',
  `material_desc` text NOT NULL,
  `localization` tinytext NOT NULL,
  `clinical_note` tinytext NOT NULL,
  `extra_note` tinytext NOT NULL,
  `repeat_note` tinytext NOT NULL,
  `gyn_last_period` varchar(25) NOT NULL DEFAULT '',
  `gyn_period_type` varchar(25) NOT NULL DEFAULT '',
  `gyn_gravida` varchar(25) NOT NULL DEFAULT '',
  `gyn_menopause_since` varchar(25) NOT NULL DEFAULT '0',
  `gyn_hysterectomy` varchar(25) NOT NULL DEFAULT '0',
  `gyn_contraceptive` varchar(25) NOT NULL DEFAULT '0',
  `gyn_iud` varchar(25) NOT NULL DEFAULT '',
  `gyn_hormone_therapy` varchar(25) NOT NULL DEFAULT '',
  `doctor_sign` varchar(35) NOT NULL DEFAULT '',
  `op_date` date NOT NULL DEFAULT '0000-00-00',
  `send_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `status` varchar(10) NOT NULL DEFAULT '',
  `entry_date` date NOT NULL DEFAULT '0000-00-00',
  `journal_nr` varchar(15) NOT NULL DEFAULT '',
  `blocks_nr` int(11) NOT NULL DEFAULT '0',
  `deep_cuts` int(11) NOT NULL DEFAULT '0',
  `special_dye` varchar(35) NOT NULL DEFAULT '',
  `immune_histochem` varchar(35) NOT NULL DEFAULT '',
  `hormone_receptors` varchar(35) NOT NULL DEFAULT '',
  `specials` varchar(35) NOT NULL DEFAULT '',
  `history` text,
  `modify_id` varchar(35) NOT NULL DEFAULT '',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `process_id` varchar(35) NOT NULL DEFAULT '',
  `process_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`batch_nr`),
  KEY `encounter_nr` (`encounter_nr`),
  KEY `send_date` (`send_date`)
);
