
DROP TABLE IF EXISTS `care_pharma_products_main`;
CREATE TABLE `care_pharma_products_main` (
  `bestellnum` varchar(12) NOT NULL DEFAULT '',
  `inventory_code` varchar(12) DEFAULT NULL,
  `artikelnum` tinytext NOT NULL,
  `industrynum` tinytext NOT NULL,
  `artikelname` tinytext NOT NULL,
  `generic` tinytext NOT NULL,
  `description` text NOT NULL,
  `packing` tinytext NOT NULL,
  `type_nr` int(10) unsigned NOT NULL DEFAULT '1',
  `prod_class` enum('M','S') NOT NULL DEFAULT 'M',
  `minorder` int(4) NOT NULL DEFAULT '0',
  `maxorder` int(4) NOT NULL DEFAULT '0',
  `proorder` tinytext NOT NULL,
  `picfile` tinytext NOT NULL,
  `encoder` tinytext NOT NULL,
  `enc_date` tinytext NOT NULL,
  `enc_time` tinytext NOT NULL,
  `lock_flag` tinyint(1) NOT NULL DEFAULT '0',
  `is_socialized` tinyint(1) NOT NULL DEFAULT '0',
  `is_restricted` tinyint(1) NOT NULL DEFAULT '0',
  `classification` int(11) DEFAULT NULL,
  `medgroup` text NOT NULL,
  `cave` tinytext NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT '',
  `price_cash` decimal(10,4) DEFAULT NULL,
  `price_charge` decimal(10,4) DEFAULT NULL,
  `unit` int(10) unsigned DEFAULT NULL,
  `history` text NOT NULL,
  `modify_id` varchar(35) NOT NULL DEFAULT '',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ref_source` varchar(10) NOT NULL DEFAULT 'PH',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `category_id` int(4) NOT NULL,
  PRIMARY KEY (`bestellnum`),
  KEY `FK_care_pharma_products_main` (`classification`),
  KEY `prodclass_index` (`prod_class`),
  KEY `FK_care_pharma_products_main_prodtype` (`type_nr`),
  CONSTRAINT `FK_care_pharma_products_main` FOREIGN KEY (`classification`) REFERENCES `seg_product_classification` (`class_code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_care_pharma_products_main_prodtype` FOREIGN KEY (`type_nr`) REFERENCES `seg_type_product` (`nr`) ON UPDATE CASCADE
);
