
DROP TABLE IF EXISTS `care_pregnancy`;
CREATE TABLE `care_pregnancy` (
  `nr` int(10) unsigned NOT NULL,
  `encounter_nr` varchar(12) NOT NULL DEFAULT '0',
  `this_pregnancy_nr` int(11) unsigned NOT NULL DEFAULT '0',
  `delivery_date` date NOT NULL DEFAULT '0000-00-00',
  `delivery_time` time NOT NULL DEFAULT '00:00:00',
  `gravida` tinyint(2) unsigned DEFAULT NULL,
  `para` tinyint(2) unsigned DEFAULT NULL,
  `pregnancy_gestational_age` tinyint(2) unsigned DEFAULT NULL,
  `nr_of_fetuses` tinyint(2) unsigned DEFAULT NULL,
  `child_encounter_nr` varchar(255) NOT NULL DEFAULT '',
  `is_booked` tinyint(1) NOT NULL DEFAULT '0',
  `vdrl` char(1) DEFAULT NULL,
  `rh` tinyint(1) DEFAULT NULL,
  `delivery_mode` tinyint(2) NOT NULL DEFAULT '0',
  `delivery_by` varchar(60) DEFAULT NULL,
  `bp_systolic_high` smallint(4) unsigned DEFAULT NULL,
  `bp_diastolic_high` smallint(4) unsigned DEFAULT NULL,
  `proteinuria` tinyint(1) DEFAULT NULL,
  `labour_duration` smallint(3) unsigned DEFAULT NULL,
  `induction_method` tinyint(2) NOT NULL DEFAULT '0',
  `induction_indication` varchar(125) DEFAULT NULL,
  `anaesth_type_nr` tinyint(2) NOT NULL DEFAULT '0',
  `is_epidural` char(1) DEFAULT NULL,
  `complications` varchar(255) DEFAULT NULL,
  `perineum` tinyint(2) NOT NULL DEFAULT '0',
  `blood_loss` float(8,2) unsigned DEFAULT NULL,
  `blood_loss_unit` varchar(10) DEFAULT NULL,
  `is_retained_placenta` char(1) NOT NULL DEFAULT '',
  `post_labour_condition` varchar(35) DEFAULT NULL,
  `outcome` varchar(35) NOT NULL DEFAULT '',
  `status` varchar(25) NOT NULL DEFAULT '',
  `history` text NOT NULL,
  `modify_id` varchar(35) NOT NULL DEFAULT '',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`nr`,`encounter_nr`),
  KEY `encounter_nr` (`encounter_nr`)
);
