
DROP TABLE IF EXISTS `care_insurance_firm`;
CREATE TABLE `care_insurance_firm` (
  `hcare_id` int(8) unsigned NOT NULL,
  `firm_id` varchar(40) NOT NULL,
  `name` varchar(60) NOT NULL DEFAULT '',
  `iso_country_id` char(3) NOT NULL DEFAULT '',
  `sub_area` varchar(60) NOT NULL DEFAULT '',
  `type_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `accreditation_no` varchar(12) NOT NULL,
  `employer_no` varchar(15) NOT NULL,
  `addr` varchar(255) DEFAULT NULL,
  `addr_mail` varchar(200) DEFAULT NULL,
  `addr_billing` varchar(200) DEFAULT NULL,
  `addr_email` varchar(60) DEFAULT NULL,
  `phone_main` varchar(35) DEFAULT NULL,
  `phone_aux` varchar(35) DEFAULT NULL,
  `fax_main` varchar(35) DEFAULT NULL,
  `fax_aux` varchar(35) DEFAULT NULL,
  `contact_person` varchar(60) DEFAULT NULL,
  `contact_phone` varchar(35) DEFAULT NULL,
  `contact_fax` varchar(35) DEFAULT NULL,
  `contact_email` varchar(60) DEFAULT NULL,
  `use_frequency` bigint(20) unsigned NOT NULL DEFAULT '0',
  `status` varchar(25) NOT NULL DEFAULT '',
  `history` text NOT NULL,
  `modify_id` varchar(35) NOT NULL DEFAULT '',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `is_rvuadjustbasis` tinyint(1) NOT NULL DEFAULT '0',
  `default_classification` varchar(5) NOT NULL,
  PRIMARY KEY (`hcare_id`),
  KEY `name` (`name`)
);
