
DROP TABLE IF EXISTS `care_encounter`;
CREATE TABLE `care_encounter` (
  `encounter_nr` varchar(12) NOT NULL,
  `pid` varchar(12) NOT NULL DEFAULT '0',
  `encounter_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `encounter_class_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `encounter_type` smallint(5) NOT NULL,
  `encounter_status` varchar(35) NOT NULL DEFAULT '',
  `official_receipt_nr` varchar(200) DEFAULT NULL,
  `er_opd_diagnosis` text,
  `consulting_dept_nr` mediumint(8) DEFAULT NULL,
  `consulting_dr_nr` int(11) DEFAULT NULL,
  `referrer_diagnosis` tinytext NOT NULL,
  `referrer_recom_therapy` tinytext,
  `referrer_dr` varchar(100) NOT NULL,
  `referrer_dept` varchar(255) NOT NULL DEFAULT '',
  `referrer_institution` varchar(255) NOT NULL DEFAULT '',
  `referrer_notes` text NOT NULL,
  `financial_class_nr` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `insurance_nr` varchar(25) DEFAULT '0',
  `insurance_firm_id` varchar(100) NOT NULL DEFAULT '0',
  `insurance_class_nr` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `insurance_2_nr` varchar(25) DEFAULT '0',
  `insurance_2_firm_id` varchar(100) NOT NULL DEFAULT '0',
  `guarantor_pid` int(11) NOT NULL DEFAULT '0',
  `contact_pid` int(11) NOT NULL DEFAULT '0',
  `contact_relation` varchar(35) NOT NULL DEFAULT '',
  `current_ward_nr` smallint(3) unsigned NOT NULL DEFAULT '0',
  `current_room_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `in_ward` tinyint(1) NOT NULL DEFAULT '0',
  `area` varchar(100) DEFAULT NULL,
  `current_dept_nr` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `in_dept` tinyint(1) NOT NULL DEFAULT '0',
  `current_firm_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `current_att_dr_nr` int(11) NOT NULL DEFAULT '0',
  `consulting_dr` varchar(60) NOT NULL,
  `extra_service` varchar(25) NOT NULL,
  `admission_dt` datetime DEFAULT NULL,
  `is_discharged` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `discharge_date` date DEFAULT NULL,
  `discharge_time` time DEFAULT NULL,
  `followup_date` date NOT NULL DEFAULT '0000-00-00',
  `followup_responsibility` varchar(255) DEFAULT NULL,
  `post_encounter_notes` text NOT NULL,
  `informant_name` varchar(60) DEFAULT NULL COMMENT 'respondent',
  `info_address` varchar(100) DEFAULT NULL,
  `relation_informant` varchar(30) DEFAULT NULL COMMENT 'respondent relation',
  `occupation` varchar(12) DEFAULT NULL,
  `source_income` varchar(35) DEFAULT NULL,
  `monthly_income` int(11) DEFAULT NULL,
  `nr_dependents` int(5) DEFAULT NULL,
  `status` varchar(25) NOT NULL,
  `history` text NOT NULL,
  `modify_id` varchar(35) NOT NULL,
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `is_medico` int(1) DEFAULT '0',
  `is_confidential` int(1) DEFAULT '0',
  `POI` varchar(300) DEFAULT NULL,
  `TOI` time DEFAULT NULL,
  `DOI` date DEFAULT NULL,
  `is_DOA` int(1) DEFAULT '0',
  `is_DOA_reason` text,
  `category` int(11) DEFAULT NULL,
  `is_served` int(1) DEFAULT '0',
  `date_served` datetime DEFAULT NULL,
  `clerk_served_by` varchar(100) DEFAULT NULL,
  `clerk_served_date` datetime DEFAULT NULL,
  `clerk_served_history` text,
  `is_maygohome` tinyint(1) DEFAULT '0',
  `mgh_setdte` datetime NOT NULL,
  `parent_encounter_nr` varchar(12) DEFAULT NULL,
  `chief_complaint` text,
  `received_date` date DEFAULT NULL,
  `smoker_history` enum('yes','no','na') DEFAULT NULL,
  `drinker_history` enum('yes','no','na') DEFAULT NULL,
  PRIMARY KEY (`encounter_nr`),
  KEY `pid` (`pid`),
  KEY `encounter_date` (`encounter_date`),
  KEY `pid_encounterdate_index` (`pid`,`encounter_date`),
  KEY `parentencounter_index` (`parent_encounter_nr`),
  KEY `status_index` (`encounter_status`),
  KEY `admissiondt_index` (`admission_dt`),
  KEY `encountertype_index` (`encounter_type`),
  KEY `dischargedate_index` (`discharge_date`),
  KEY `createtime_index` (`create_time`),
  KEY `currentwardnr_index` (`current_ward_nr`),
  CONSTRAINT `FK_care_encounter_person` FOREIGN KEY (`pid`) REFERENCES `care_person` (`pid`) ON UPDATE CASCADE
);
;
DELIMITER ;
;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
