
DROP TABLE IF EXISTS `care_neonatal`;
CREATE TABLE `care_neonatal` (
  `nr` int(11) unsigned NOT NULL,
  `pid` varchar(12) NOT NULL DEFAULT '0',
  `delivery_date` date NOT NULL DEFAULT '0000-00-00',
  `parent_encounter_nr` int(11) unsigned NOT NULL DEFAULT '0',
  `delivery_nr` tinyint(4) NOT NULL DEFAULT '0',
  `encounter_nr` int(11) unsigned NOT NULL DEFAULT '0',
  `delivery_place` varchar(60) NOT NULL DEFAULT '',
  `delivery_mode` tinyint(2) NOT NULL DEFAULT '0',
  `c_s_reason` text,
  `born_before_arrival` tinyint(1) DEFAULT '0',
  `face_presentation` tinyint(1) NOT NULL DEFAULT '0',
  `posterio_occipital_position` tinyint(1) NOT NULL DEFAULT '0',
  `delivery_rank` tinyint(2) unsigned NOT NULL DEFAULT '1',
  `apgar_1_min` tinyint(4) NOT NULL DEFAULT '0',
  `apgar_5_min` tinyint(4) NOT NULL DEFAULT '0',
  `apgar_10_min` tinyint(4) NOT NULL DEFAULT '0',
  `time_to_spont_resp` tinyint(2) DEFAULT NULL,
  `condition` varchar(60) DEFAULT '0',
  `weight` float(8,2) unsigned DEFAULT NULL,
  `length` float(8,2) unsigned DEFAULT NULL,
  `head_circumference` float(8,2) unsigned DEFAULT NULL,
  `scored_gestational_age` float(4,2) unsigned DEFAULT NULL,
  `feeding` tinyint(4) NOT NULL DEFAULT '0',
  `congenital_abnormality` varchar(125) NOT NULL DEFAULT '',
  `classification` varchar(255) NOT NULL DEFAULT '0',
  `disease_category` tinyint(2) NOT NULL DEFAULT '0',
  `outcome` tinyint(2) NOT NULL DEFAULT '0',
  `status` varchar(25) NOT NULL DEFAULT '',
  `history` text,
  `modify_id` varchar(35) NOT NULL DEFAULT '',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`nr`),
  KEY `pid` (`pid`),
  KEY `pregnancy_nr` (`parent_encounter_nr`),
  KEY `encounter_nr` (`encounter_nr`),
  CONSTRAINT `FK_care_neonatal` FOREIGN KEY (`pid`) REFERENCES `care_person` (`pid`) ON UPDATE CASCADE
);
