
DROP TABLE IF EXISTS `care_personell`;
CREATE TABLE `care_personell` (
  `nr` int(11) NOT NULL,
  `short_id` varchar(10) DEFAULT NULL,
  `pid` varchar(12) NOT NULL DEFAULT '0',
  `job_type_nr` int(11) NOT NULL DEFAULT '0',
  `job_function_title` varchar(60) DEFAULT NULL,
  `job_position` varchar(100) DEFAULT NULL,
  `date_join` date DEFAULT NULL,
  `date_exit` date DEFAULT NULL,
  `contract_class` varchar(35) NOT NULL DEFAULT '0',
  `contract_start` date DEFAULT NULL,
  `contract_end` date DEFAULT NULL,
  `is_discharged` tinyint(1) NOT NULL DEFAULT '0',
  `pay_class` varchar(25) NOT NULL,
  `pay_class_sub` varchar(25) NOT NULL,
  `local_premium_id` varchar(5) NOT NULL,
  `tax_account_nr` varchar(60) NOT NULL,
  `ir_code` varchar(25) NOT NULL,
  `nr_workday` tinyint(1) NOT NULL DEFAULT '0',
  `nr_weekhour` float(10,2) NOT NULL DEFAULT '0.00',
  `nr_vacation_day` tinyint(2) NOT NULL DEFAULT '0',
  `multiple_employer` tinyint(1) NOT NULL DEFAULT '0',
  `nr_dependent` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `status` varchar(25) NOT NULL,
  `history` text NOT NULL,
  `modify_id` varchar(35) NOT NULL,
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `license_nr` varchar(20) DEFAULT NULL,
  `prescription_license_nr` varchar(20) DEFAULT NULL,
  `tin` varchar(20) DEFAULT NULL,
  `is_resident_dr` tinyint(1) DEFAULT '0',
  `tier_nr` int(10) unsigned NOT NULL,
  `other_title` varchar(50) DEFAULT NULL,
  `ward_nr` smallint(5) unsigned DEFAULT '0',
  `is_reliever` tinyint(1) DEFAULT '0',
  `newpid` varchar(12) DEFAULT NULL,
  `is_housecase_attdr` tinyint(1) NOT NULL DEFAULT '0',
  `is_housecase_surgeon` tinyint(1) NOT NULL DEFAULT '0',
  `is_housecase_anesth` tinyint(1) NOT NULL DEFAULT '0',
  `ptr_nr` varchar(20) DEFAULT NULL,
  `s2_nr` varchar(20) DEFAULT NULL,
  `doctor_role` varchar(6) DEFAULT NULL,
  `doctor_level` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`nr`),
  UNIQUE KEY `pid` (`pid`),
  CONSTRAINT `FK_care_personell_person` FOREIGN KEY (`pid`) REFERENCES `care_person` (`pid`) ON DELETE CASCADE ON UPDATE CASCADE
);
