
DROP TABLE IF EXISTS `care_department`;
CREATE TABLE `care_department` (
  `nr` mediumint(8) unsigned NOT NULL,
  `id` varchar(60) NOT NULL DEFAULT '',
  `type` varchar(25) NOT NULL,
  `name_formal` varchar(60) NOT NULL DEFAULT '',
  `name_short` varchar(35) NOT NULL DEFAULT '',
  `name_alternate` varchar(225) DEFAULT NULL,
  `LD_var` varchar(35) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `admit_inpatient` tinyint(1) NOT NULL DEFAULT '0',
  `admit_outpatient` tinyint(1) NOT NULL DEFAULT '0',
  `has_oncall_doc` tinyint(1) NOT NULL DEFAULT '1',
  `has_oncall_nurse` tinyint(1) NOT NULL DEFAULT '1',
  `does_surgery` tinyint(1) NOT NULL DEFAULT '0',
  `this_institution` tinyint(1) NOT NULL DEFAULT '1',
  `is_sub_dept` tinyint(1) NOT NULL DEFAULT '0',
  `parent_dept_nr` tinyint(3) unsigned DEFAULT NULL,
  `work_hours` varchar(100) DEFAULT NULL,
  `consult_hours` varchar(100) DEFAULT NULL,
  `is_inactive` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `address` text,
  `sig_line` varchar(60) DEFAULT NULL,
  `sig_stamp` text,
  `logo_mime_type` varchar(5) DEFAULT NULL,
  `status` varchar(25) NOT NULL DEFAULT '',
  `history` text,
  `modify_id` varchar(35) NOT NULL DEFAULT '',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `for_male_only` tinyint(1) DEFAULT '0',
  `for_female_only` tinyint(1) DEFAULT '0',
  `for_child_only` tinyint(1) DEFAULT '0',
  `child_age_limit` int(2) DEFAULT NULL,
  PRIMARY KEY (`nr`),
  UNIQUE KEY `id` (`id`)
);
