
DROP TABLE IF EXISTS `seg_or_main`;
CREATE TABLE `seg_or_main` (
  `or_main_refno` bigint(20) unsigned NOT NULL,
  `ceo_refno` varchar(12) NOT NULL DEFAULT '',
  `encounter_nr` varchar(12) NOT NULL,
  `trans_type` smallint(5) DEFAULT NULL,
  `date_request` datetime DEFAULT NULL,
  `or_procedure` text,
  `procedure_id` smallint(5) unsigned DEFAULT NULL,
  `request_flag` varchar(10) DEFAULT NULL,
  `request_source` varchar(10) DEFAULT NULL,
  `special_requirements` text,
  `final_date_operation` date DEFAULT NULL,
  `date_operation` date DEFAULT NULL,
  `history` text NOT NULL,
  `time_operation` varchar(14) DEFAULT NULL,
  `dr_nr` int(11) DEFAULT NULL,
  `pre_op_checklist` text,
  `create_id` varchar(35) NOT NULL,
  `create_dt` timestamp NULL DEFAULT NULL,
  `modify_id` varchar(35) NOT NULL,
  `modify_dt` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `status` varchar(11) DEFAULT NULL,
  `dept_nr` mediumint(8) unsigned DEFAULT NULL,
  `is_main` smallint(2) unsigned DEFAULT NULL,
  `or_type` varchar(15) DEFAULT NULL,
  `request_priority` varchar(10) DEFAULT NULL,
  `remarks` text,
  `room_nr` int(11) DEFAULT NULL,
  `bed_nr` int(11) DEFAULT NULL,
  `length_op` varchar(30) DEFAULT NULL,
  `done_date` timestamp NULL DEFAULT NULL,
  `consent_signed` tinyint(4) DEFAULT NULL,
  `or_case` varchar(20) DEFAULT NULL,
  `est_length_op` varchar(30) DEFAULT NULL,
  `case_classification` varchar(25) DEFAULT NULL,
  `pre_op_diagnosis` text,
  `operation_procedure` text,
  `created_id` varchar(35) DEFAULT NULL,
  `created_date` timestamp NULL DEFAULT NULL,
  `modified_id` varchar(35) DEFAULT NULL,
  `modified_date` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`or_main_refno`)
);
