
DROP TABLE IF EXISTS `seg_radio_mri_history`;
CREATE TABLE `seg_radio_mri_history` (
  `uuid` varchar(50) NOT NULL,
  `encounter_nr` varchar(12) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `refno` varchar(12) DEFAULT '0',
  `request_date` datetime DEFAULT NULL,
  `create_tm` datetime DEFAULT NULL,
  `modify_id` varchar(60) DEFAULT NULL,
  `modify_tm` datetime DEFAULT NULL,
  `request` varchar(50) DEFAULT NULL,
  `total` varchar(50) DEFAULT NULL,
  `discount` varchar(50) DEFAULT NULL,
  `transaction` varchar(50) DEFAULT NULL,
  `priority` tinyint(1) DEFAULT '0',
  `create_id` varchar(60) DEFAULT NULL,
  `dr_nr` varchar(50) DEFAULT NULL,
  `dr_name` varchar(150) DEFAULT NULL,
  `dr_contact_nr` varchar(50) DEFAULT NULL,
  `dr_phone` varchar(50) DEFAULT NULL,
  `refer_date` datetime DEFAULT NULL,
  `dr_address` text,
  `mri_dr_nr` varchar(50) DEFAULT NULL,
  `mri_dr_name` varchar(150) DEFAULT NULL,
  `history` text,
  `chief_comp` text,
  `phy_exam` text,
  `impression` text,
  `past_med_his` text,
  `creatinine` varchar(50) DEFAULT NULL,
  `bun` varchar(50) DEFAULT NULL,
  `purpose` tinyint(1) DEFAULT '0',
  `dr_specialty` text,
  `info_gain` text,
  `med_prob` text,
  `pid` int(12) DEFAULT NULL,
  `encoder` varchar(50) DEFAULT NULL,
  `group_code` varchar(50) DEFAULT NULL,
  `mp_amount` varchar(50) DEFAULT NULL,
  `mp_request` varchar(250) DEFAULT NULL,
  `mp_trans_type` varchar(250) DEFAULT NULL,
  `mp_total` varchar(50) DEFAULT NULL,
  `add_impression` text,
  PRIMARY KEY (`uuid`)
);
