
DROP TABLE IF EXISTS `seg_or_main_post`;
CREATE TABLE `seg_or_main_post` (
  `or_main_refno_post` bigint(20) unsigned NOT NULL,
  `or_main_refno` bigint(20) unsigned DEFAULT NULL,
  `time_started` time DEFAULT NULL,
  `time_finished` time DEFAULT NULL,
  `post_op_diagnosis` text,
  `created_id` varchar(35) DEFAULT NULL,
  `modified_id` varchar(35) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `modified_date` date DEFAULT NULL,
  `history` text,
  `intra_operative` text,
  `post_operative` text,
  `or_status` text,
  `or_technique` text,
  `sponge_count` int(10) unsigned DEFAULT NULL,
  `sutures` text,
  `sponge_os` text,
  `sponge_ap` text,
  `sponge_cb` text,
  `sponge_pp` text,
  `sponge_peanuts` text,
  `needle_count` int(10) unsigned DEFAULT NULL,
  `instrument_count` int(10) unsigned DEFAULT NULL,
  `transferred_to` smallint(5) unsigned DEFAULT NULL,
  `operation_performed` text,
  `fluids` text,
  `drain_inserted` text,
  `packs_inserted` text,
  `blood_replacement` text,
  `blood_loss` text,
  `tissues_removed` text,
  `remarks` text,
  PRIMARY KEY (`or_main_refno_post`),
  KEY `FK_seg_or_main_post` (`or_main_refno`),
  KEY `FK_seg_or_main_post2` (`transferred_to`),
  CONSTRAINT `FK_seg_or_main_post` FOREIGN KEY (`or_main_refno`) REFERENCES `seg_or_main` (`or_main_refno`) ON DELETE CASCADE ON UPDATE CASCADE
);
