
DROP TABLE IF EXISTS `seg_radio_ct_history`;
CREATE TABLE `seg_radio_ct_history` (
  `uuid` varchar(50) NOT NULL,
  `encounter_nr` varchar(12) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `refno` varchar(12) DEFAULT '0',
  `request_date` datetime NOT NULL,
  `doctor_nr` varchar(10) DEFAULT NULL,
  `subj_comp` text,
  `obj_comp` text,
  `assessment` text,
  `has_conscious` tinyint(1) DEFAULT '1',
  `did_vomit` tinyint(1) DEFAULT '0',
  `gcs` varchar(100) DEFAULT NULL,
  `rls` varchar(100) DEFAULT NULL,
  `had_surgery` tinyint(1) DEFAULT '0',
  `surgery_date` date DEFAULT '0000-00-00',
  `surgery_proc` text,
  `laboratory` tinyint(1) DEFAULT '0',
  `has_blood_chem` tinyint(1) DEFAULT '0',
  `has_xray` tinyint(1) DEFAULT '0',
  `has_ultrasound` tinyint(1) DEFAULT '0',
  `has_ct_mri` tinyint(1) DEFAULT '0',
  `has_biopsy` tinyint(1) DEFAULT '0',
  `date_blood_chem` datetime DEFAULT NULL,
  `date_xray` datetime DEFAULT NULL,
  `date_ultrasound` datetime DEFAULT NULL,
  `date_ct_mri` datetime DEFAULT NULL,
  `create_tm` datetime DEFAULT NULL,
  `modify_id` varchar(60) DEFAULT NULL,
  `modify_tm` datetime DEFAULT NULL,
  `history` time DEFAULT NULL,
  `create_id` varchar(60) DEFAULT NULL,
  `date_biopsy` datetime DEFAULT NULL,
  `medico_legal` tinyint(1) DEFAULT '0',
  `cln_imp` text,
  `chf_cmp` text,
  `bld_chm_res` text,
  `bld_chm_rem` text,
  `xray_res` text,
  `xray_rem` text,
  `ultrasound_res` text,
  `ultrasound_rem` text,
  `ct_mri_res` text,
  `ct_mri_rem` text,
  `biopsy_res` text,
  `biopsy_rem` text,
  `noi` text,
  `doi` datetime DEFAULT NULL,
  `poi` text,
  `toi` time DEFAULT NULL,
  `dr_name` varchar(150) DEFAULT NULL,
  `priority` tinyint(1) DEFAULT '0',
  `request` varchar(50) DEFAULT NULL,
  `total` varchar(50) DEFAULT NULL,
  `discount` varchar(50) DEFAULT NULL,
  `transaction` varchar(50) DEFAULT NULL,
  `pid` int(12) DEFAULT NULL,
  `encoder` varchar(50) DEFAULT NULL,
  `group_code` varchar(50) DEFAULT NULL,
  `mp_amount` varchar(50) DEFAULT NULL,
  `mp_request` varchar(250) DEFAULT NULL,
  `mp_trans_type` varchar(250) DEFAULT NULL,
  `mp_total` varchar(50) DEFAULT NULL,
  `add_impression` text,
  PRIMARY KEY (`uuid`,`request_date`)
);
