
DROP TABLE IF EXISTS `seg_cert_death_fetal`;
CREATE TABLE `seg_cert_death_fetal` (
  `pid` varchar(12) NOT NULL,
  `registry_nr` varchar(12) DEFAULT NULL,
  `birth_place_basic` varchar(100) DEFAULT NULL,
  `birth_place_mun` varchar(50) DEFAULT NULL,
  `birth_place_prov` varchar(50) DEFAULT NULL,
  `birth_type` tinyint(4) DEFAULT NULL,
  `birth_rank` varchar(20) DEFAULT NULL,
  `delivery_method` varchar(25) DEFAULT NULL,
  `birth_order` varchar(15) DEFAULT NULL,
  `birth_weight` int(8) DEFAULT NULL,
  `m_name_first` varchar(50) DEFAULT NULL,
  `m_name_middle` varchar(50) DEFAULT NULL,
  `m_name_last` varchar(50) DEFAULT NULL,
  `m_citizenship` varchar(25) DEFAULT NULL,
  `m_religion` smallint(6) DEFAULT NULL,
  `m_occupation` smallint(6) DEFAULT NULL,
  `m_age` tinyint(4) DEFAULT NULL,
  `m_total_alive` tinyint(4) DEFAULT NULL,
  `m_still_living` tinyint(4) DEFAULT NULL,
  `m_now_dead` tinyint(4) DEFAULT NULL,
  `m_residence_basic` varchar(125) DEFAULT NULL,
  `m_residence_brgy` int(11) DEFAULT NULL,
  `m_residence_mun` int(11) DEFAULT NULL,
  `m_residence_prov` int(11) DEFAULT NULL,
  `f_name_first` varchar(50) DEFAULT NULL,
  `f_name_middle` varchar(50) DEFAULT NULL,
  `f_name_last` varchar(50) DEFAULT NULL,
  `f_citizenship` varchar(25) DEFAULT NULL,
  `f_religion` smallint(6) DEFAULT NULL,
  `f_occupation` smallint(6) DEFAULT NULL,
  `f_age` tinyint(4) DEFAULT NULL,
  `parent_marriage_date` date DEFAULT NULL,
  `parent_marriage_place` varchar(250) DEFAULT NULL,
  `death_cause` text,
  `death_occurrence` varchar(25) DEFAULT NULL,
  `pregnancy_length` tinyint(4) DEFAULT NULL,
  `attendant_type` varchar(30) DEFAULT NULL,
  `death_time` time DEFAULT '00:00:00',
  `attendant_name` int(11) DEFAULT NULL,
  `attendant_title` varchar(25) DEFAULT NULL,
  `attendant_address` varchar(125) DEFAULT NULL,
  `attendant_date_sign` date DEFAULT '0000-00-00',
  `corpse_disposal` varchar(50) DEFAULT NULL,
  `burial_permit` varchar(20) DEFAULT NULL,
  `burial_date_issued` date DEFAULT '0000-00-00',
  `is_autopsy` tinyint(1) DEFAULT NULL,
  `cemetery_name_address` varchar(250) DEFAULT NULL,
  `informant_name` varchar(100) DEFAULT NULL,
  `informant_relation` varchar(100) DEFAULT NULL,
  `informant_address` varchar(125) DEFAULT NULL,
  `informant_date_sign` date DEFAULT '0000-00-00',
  `encoder_name` varchar(100) DEFAULT NULL,
  `encoder_title` varchar(25) DEFAULT NULL,
  `encoder_date_sign` date DEFAULT '0000-00-00',
  `history` text,
  `modify_id` varchar(50) DEFAULT NULL,
  `modify_dt` datetime DEFAULT NULL,
  `create_id` varchar(50) DEFAULT NULL,
  `create_dt` datetime DEFAULT NULL,
  PRIMARY KEY (`pid`),
  CONSTRAINT `FK_seg_cert_death_fetal` FOREIGN KEY (`pid`) REFERENCES `care_person` (`pid`) ON UPDATE CASCADE
);
