
DROP TABLE IF EXISTS `seg_dialysis_request`;
CREATE TABLE `seg_dialysis_request` (
  `refno` varchar(12) NOT NULL,
  `encounter_nr` varchar(12) NOT NULL,
  `pid` varchar(12) DEFAULT NULL,
  `request_date` datetime DEFAULT NULL,
  `is_cash` tinyint(1) DEFAULT '0',
  `request_type` enum('PRE','POST') DEFAULT NULL,
  `session_type` enum('MORNING','AFTERNOON','EVENING','STAT','INPATIENT') DEFAULT NULL,
  `schedule_day` enum('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY','CMAP','LINGAP') DEFAULT NULL,
  `request_name` varchar(200) DEFAULT NULL,
  `requesting_doctor` int(11) unsigned DEFAULT NULL,
  `attending_nurse` int(11) unsigned DEFAULT NULL,
  `remarks` text,
  `machine_id` char(36) DEFAULT NULL,
  `vitalsign_no` bigint(20) unsigned DEFAULT NULL,
  `dialyzer_usage` enum('1ST','2ND','3RD','4TH','5TH','NEW') DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `request_source` varchar(20) NOT NULL DEFAULT 'RDU',
  `history` text,
  `create_time` datetime DEFAULT NULL,
  `create_id` varchar(12) DEFAULT NULL,
  `modify_time` datetime DEFAULT NULL,
  `modify_id` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`refno`),
  KEY `FK_seg_dialysis_request_encounter` (`encounter_nr`),
  KEY `FK_seg_dialysis_request_vitalsign` (`vitalsign_no`),
  KEY `FK_seg_dialysis_request_source` (`request_source`),
  KEY `FK_seg_dialysis_request_machine` (`machine_id`),
  CONSTRAINT `FK_seg_dialysis_request_encounter` FOREIGN KEY (`encounter_nr`) REFERENCES `care_encounter` (`encounter_nr`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_seg_dialysis_request_machine` FOREIGN KEY (`machine_id`) REFERENCES `seg_dialysis_machine` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_seg_dialysis_request_source` FOREIGN KEY (`request_source`) REFERENCES `seg_type_request_source` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_seg_dialysis_request_vitalsign` FOREIGN KEY (`vitalsign_no`) REFERENCES `seg_encounter_vitalsigns` (`vitalsign_no`) ON DELETE CASCADE ON UPDATE CASCADE
);
