
DROP TABLE IF EXISTS `seg_lab_servdetails_blood`;
CREATE TABLE `seg_lab_servdetails_blood` (
  `refno` varchar(12) NOT NULL,
  `service_code` varchar(10) NOT NULL,
  `price_cash` decimal(10,2) DEFAULT '0.00',
  `price_cash_orig` decimal(10,2) DEFAULT '0.00',
  `price_charge` decimal(10,2) DEFAULT '0.00',
  `request_doctor` varchar(50) DEFAULT NULL,
  `request_dept` varchar(50) DEFAULT NULL,
  `is_in_house` tinyint(1) DEFAULT NULL,
  `clinical_info` text,
  `status` enum('pending','done','deleted','sent-out') DEFAULT 'pending',
  `is_forward` tinyint(1) DEFAULT '0',
  `is_served` tinyint(1) DEFAULT '0',
  `date_served` datetime DEFAULT NULL,
  `clerk_served_by` varchar(100) DEFAULT NULL,
  `clerk_served_date` datetime DEFAULT NULL,
  `quantity` double DEFAULT '1',
  `old_qty_request` double DEFAULT '0',
  `reason_sent_out` text,
  `sent_out_date` datetime DEFAULT NULL,
  `sent_out_by` varchar(100) DEFAULT NULL,
  `is_monitor` tinyint(1) DEFAULT '0',
  `parent_refno` varchar(12) DEFAULT NULL,
  `request_flag` varchar(10) DEFAULT NULL,
  `no_gel_tubes` double DEFAULT '0',
  `cancel_reason` text,
  `is_posted_lis` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`refno`,`service_code`),
  KEY `FK_seg_lab_servdetails2` (`service_code`),
  KEY `FK_seg_lab_servdetails_charge` (`request_flag`),
  CONSTRAINT `FK_seg_lab_servdetails_blood` FOREIGN KEY (`refno`) REFERENCES `seg_lab_serv_blood` (`refno`) ON DELETE NO ACTION ON UPDATE CASCADE
);
