
DROP TABLE IF EXISTS `seg_rep_medrec_patient_icd_tbl`;
CREATE TABLE `seg_rep_medrec_patient_icd_tbl` (
  `type_nr` smallint(5) DEFAULT NULL,
  `icd_type` varchar(9) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `code_parent` varchar(25) DEFAULT '',
  `icd` varchar(25) DEFAULT '',
  `icd_desc` text,
  `encounter_nr` varchar(12) NOT NULL,
  `patient_name` varchar(183) DEFAULT NULL,
  `diagnosis` text,
  `admission_dt` datetime DEFAULT NULL,
  `date_birth` date NOT NULL DEFAULT '0000-00-00',
  `discharge_date` date DEFAULT NULL,
  `age` varbinary(25) DEFAULT NULL,
  `sex` varchar(1) NOT NULL DEFAULT '',
  `address` varchar(431) DEFAULT NULL,
  `if_dengue` char(0) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `fatality` varbinary(10) NOT NULL DEFAULT '',
  `physician` varchar(100) DEFAULT NULL,
  `encounter_type` smallint(5) NOT NULL,
  `create_date` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `encounter_class_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `encounter_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `pid` varchar(12) NOT NULL DEFAULT '0',
  `chief_complaint` text,
  `received_date` date DEFAULT NULL,
  `current_dept_nr` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `current_att_dr_nr` int(11) NOT NULL DEFAULT '0',
  `current_ward_nr` smallint(3) unsigned NOT NULL DEFAULT '0',
  `current_room_nr` smallint(5) unsigned NOT NULL DEFAULT '0',
  `area` varchar(100) DEFAULT NULL,
  `admission_dt2` datetime DEFAULT NULL,
  `is_discharged` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `discharge_time` time DEFAULT NULL,
  `consulting_dept_nr` mediumint(8) DEFAULT NULL,
  `consulting_dr_nr` int(11) DEFAULT NULL,
  `encounter_status` varchar(35) NOT NULL DEFAULT '',
  `is_DOA` int(1) DEFAULT '0',
  `is_confidential` int(1) DEFAULT '0',
  `death_date` date DEFAULT NULL,
  `death_time` time DEFAULT NULL,
  `death_encounter_nr` int(10) DEFAULT NULL,
  `result_code` int(11) DEFAULT NULL,
  `disp_code` int(11) DEFAULT NULL,
  `cond_code` int(11) DEFAULT NULL,
  KEY `FK_seg_rep_medrec_patient_icd_tbl_enc` (`encounter_nr`),
  KEY `FK_seg_rep_medrec_patient_icd_tbl` (`pid`)
);
