
DROP TABLE IF EXISTS `seg_industrial_cert_med_driver`;
CREATE TABLE `seg_industrial_cert_med_driver` (
  `cert_nr` int(12) unsigned NOT NULL,
  `refno` varchar(12) DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `height_unit` tinyint(1) DEFAULT NULL,
  `weight` varchar(5) DEFAULT NULL,
  `weight_unit` tinyint(1) DEFAULT NULL,
  `systole` int(5) DEFAULT NULL,
  `diastole` int(5) DEFAULT NULL,
  `general_physique` varchar(12) DEFAULT NULL,
  `abnormality` text,
  `contagious_diseases` text,
  `left_eye_snellen` int(5) DEFAULT NULL,
  `right_eye_snellen` int(5) DEFAULT NULL,
  `left_eye_acuity` tinyint(1) DEFAULT NULL,
  `right_eye_acuity` tinyint(1) DEFAULT NULL,
  `left_ear` tinyint(1) DEFAULT NULL,
  `right_ear` tinyint(1) DEFAULT NULL,
  `left_lower_extremities` tinyint(1) DEFAULT NULL,
  `right_lower_extremities` tinyint(1) DEFAULT NULL,
  `remarks` text,
  `comment_drive` tinyint(1) DEFAULT NULL,
  `conditions` int(2) DEFAULT NULL,
  `educ_attain_nr` int(2) DEFAULT NULL,
  `work_status_nr` int(2) DEFAULT NULL,
  `employ_nr` int(2) DEFAULT NULL,
  `vehicle_nr` int(2) DEFAULT NULL,
  `create_dt` datetime DEFAULT NULL,
  `create_id` varchar(100) DEFAULT NULL,
  `modify_dt` datetime DEFAULT NULL,
  `modify_id` varchar(100) DEFAULT NULL,
  `history` text,
  `left_eye_other` int(1) DEFAULT NULL,
  `right_eye_other` int(1) DEFAULT NULL,
  `left_upper_extremities` tinyint(1) DEFAULT NULL,
  `right_upper_extremities` tinyint(1) DEFAULT NULL,
  `exam_physician` varchar(12) DEFAULT NULL,
  `with_disease` tinyint(1) DEFAULT NULL,
  `control_number` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`cert_nr`),
  KEY `FK_seg_industrial_cert_med_driver` (`refno`),
  CONSTRAINT `FK_seg_industrial_cert_med_driver` FOREIGN KEY (`refno`) REFERENCES `seg_industrial_transaction` (`refno`) ON DELETE CASCADE ON UPDATE CASCADE
);
