
DROP TABLE IF EXISTS `seg_lab_services`;
CREATE TABLE `seg_lab_services` (
  `code_num` int(11) DEFAULT NULL,
  `service_code` varchar(10) NOT NULL,
  `group_code` varchar(10) NOT NULL,
  `name` varchar(100) NOT NULL,
  `price_cash` decimal(10,2) NOT NULL DEFAULT '0.00',
  `price_charge` decimal(10,2) NOT NULL DEFAULT '0.00',
  `status` varchar(35) DEFAULT NULL,
  `history` text,
  `modify_id` varchar(35) NOT NULL,
  `modify_dt` datetime DEFAULT '0000-00-00 00:00:00',
  `create_id` varchar(35) NOT NULL,
  `create_dt` datetime DEFAULT '0000-00-00 00:00:00',
  `is_socialized` tinyint(1) NOT NULL DEFAULT '0',
  `is_ER` tinyint(1) DEFAULT '0',
  `is_package` tinyint(1) DEFAULT '0',
  `only_in_clinic` tinyint(1) DEFAULT '1',
  `with_result` tinyint(1) DEFAULT '1',
  `female_only` tinyint(1) DEFAULT '1',
  `male_only` tinyint(1) DEFAULT '1',
  `is_other` tinyint(1) DEFAULT '0',
  `with_inventory` tinyint(1) DEFAULT '0',
  `remarks` text,
  `oservice_code` varchar(10) DEFAULT NULL,
  `ipdservice_code` varchar(10) DEFAULT NULL,
  `area` enum('LB','SL','BB','IC') DEFAULT NULL,
  `in_lis` tinyint(1) DEFAULT '0',
  `is_med` tinyint(1) DEFAULT '0',
  `has_group_stat` tinyint(1) DEFAULT '0',
  `has_param_group` tinyint(1) DEFAULT '0',
  `in_phs` tinyint(1) DEFAULT '0',
  `is_serial` tinyint(1) DEFAULT '0',
  `no_serial` smallint(2) DEFAULT NULL,
  `is_blood_product` tinyint(1) DEFAULT '0',
  `is_profile` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`service_code`),
  KEY `FK_seg_lab_services` (`group_code`),
  CONSTRAINT `FK_seg_lab_services` FOREIGN KEY (`group_code`) REFERENCES `seg_lab_service_groups` (`group_code`) ON UPDATE CASCADE
);
