
DROP TABLE IF EXISTS `seg_socserv_patient`;
CREATE TABLE `seg_socserv_patient` (
  `mss_no` varchar(12) NOT NULL DEFAULT '',
  `pid` varchar(12) DEFAULT '',
  `encounter_nr` varchar(12) NOT NULL DEFAULT '',
  `informant_name` varchar(60) DEFAULT NULL,
  `religion` varchar(60) DEFAULT NULL,
  `contact_no` varchar(20) DEFAULT NULL,
  `companion` varchar(30) DEFAULT NULL,
  `date_interview` date DEFAULT NULL,
  `info_address` varchar(100) DEFAULT NULL,
  `relation_informant` varchar(30) DEFAULT NULL,
  `educational_attain` int(5) DEFAULT NULL,
  `occupation` int(5) DEFAULT NULL,
  `other_occupation` varchar(20) DEFAULT NULL,
  `employer` varchar(100) DEFAULT NULL,
  `employer_address` text,
  `source_income` varchar(300) DEFAULT NULL,
  `monthly_income` varchar(100) DEFAULT NULL,
  `nr_dependents` int(5) DEFAULT NULL,
  `nr_children` int(5) DEFAULT NULL,
  `per_capita_income` varchar(100) DEFAULT NULL,
  `hauz_lot_expense` varchar(20) DEFAULT NULL,
  `food_expense` varchar(20) DEFAULT NULL,
  `light_source` varchar(10) DEFAULT NULL,
  `ligth_expense` varchar(20) DEFAULT NULL,
  `water_source` varchar(10) DEFAULT NULL,
  `water_expense` varchar(20) DEFAULT NULL,
  `transport_expense` varchar(20) DEFAULT NULL,
  `other_expense` varchar(20) DEFAULT NULL,
  `status` varchar(25) DEFAULT NULL,
  `history` text,
  `modify_id` varchar(35) DEFAULT NULL,
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(35) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `education_expense` varchar(20) DEFAULT NULL,
  `househelp_expense` varchar(20) DEFAULT NULL,
  `fuel_source` varchar(10) DEFAULT NULL,
  `fuel_expense` varchar(20) DEFAULT NULL,
  `clothing_expense` varchar(20) DEFAULT NULL,
  `med_expenditure` varchar(20) DEFAULT NULL,
  `insurance_mortgage` varchar(20) DEFAULT NULL,
  `total_monthly_expense` varchar(20) DEFAULT NULL,
  `address` text,
  `house_type` int(5) DEFAULT NULL,
  `final_diagnosis` text,
  `duration_problem` varchar(50) DEFAULT NULL,
  `duration_treatment` varchar(50) DEFAULT NULL,
  `treatment_plan` text,
  `accessibility_problem` text,
  `name_referral` varchar(50) DEFAULT NULL,
  `source_referral` varchar(10) DEFAULT NULL,
  `info_agency` varchar(50) DEFAULT NULL,
  `info_contact_no` varchar(20) DEFAULT NULL,
  `remarks` text,
  `social_worker` varchar(50) DEFAULT NULL,
  `income` varchar(20) DEFAULT NULL,
  `other_income` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`mss_no`,`encounter_nr`),
  KEY `status_index` (`status`),
  KEY `encounternr_index` (`encounter_nr`),
  CONSTRAINT `FK_seg_socserv_patient` FOREIGN KEY (`mss_no`) REFERENCES `seg_social_patient` (`mss_no`) ON DELETE CASCADE ON UPDATE CASCADE
);
