
DROP TABLE IF EXISTS `seg_cert_birth`;
CREATE TABLE `seg_cert_birth` (
  `pid` varchar(12) NOT NULL,
  `registry_nr` varchar(12) DEFAULT NULL,
  `birth_place_basic` varchar(100) DEFAULT NULL,
  `birth_place_mun` varchar(50) DEFAULT NULL,
  `birth_place_prov` varchar(50) DEFAULT NULL,
  `birth_type` tinyint(4) DEFAULT NULL,
  `birth_rank` varchar(20) DEFAULT NULL,
  `birth_order` varchar(15) DEFAULT NULL,
  `birth_weight` int(11) DEFAULT NULL,
  `m_name_first` varchar(50) DEFAULT NULL,
  `m_name_middle` varchar(50) DEFAULT NULL,
  `m_name_last` varchar(50) DEFAULT NULL,
  `m_citizenship` varchar(25) DEFAULT NULL,
  `m_religion` smallint(6) DEFAULT NULL,
  `m_occupation` smallint(6) DEFAULT NULL,
  `m_ethnic` smallint(6) DEFAULT NULL,
  `m_age` tinyint(4) DEFAULT NULL,
  `m_total_alive` tinyint(4) DEFAULT NULL,
  `m_still_living` tinyint(4) DEFAULT NULL,
  `m_now_dead` tinyint(4) DEFAULT NULL,
  `m_fetal_death` tinyint(4) DEFAULT '0',
  `m_residence_basic` varchar(125) DEFAULT NULL,
  `m_residence_brgy` int(11) DEFAULT NULL,
  `m_residence_mun` int(11) DEFAULT NULL,
  `m_residence_prov` int(11) DEFAULT NULL,
  `m_residence_country` varchar(3) DEFAULT NULL,
  `f_name_first` varchar(50) DEFAULT NULL,
  `f_name_middle` varchar(50) DEFAULT NULL,
  `f_name_last` varchar(50) DEFAULT NULL,
  `f_citizenship` varchar(25) DEFAULT NULL,
  `f_religion` smallint(6) DEFAULT NULL,
  `f_occupation` smallint(6) DEFAULT NULL,
  `f_ethnic` smallint(6) DEFAULT NULL,
  `f_age` tinyint(4) DEFAULT NULL,
  `f_residence_basic` varchar(125) DEFAULT NULL,
  `f_residence_brgy` int(11) DEFAULT NULL,
  `f_residence_mun` int(11) DEFAULT NULL,
  `f_residence_prov` int(11) DEFAULT NULL,
  `f_residence_country` varchar(3) DEFAULT NULL,
  `is_married` tinyint(1) DEFAULT NULL,
  `parent_marriage_date` date DEFAULT NULL,
  `parent_marriage_place` varchar(250) DEFAULT NULL,
  `f_com_tax_nr` varchar(15) DEFAULT NULL,
  `f_com_tax_date` date DEFAULT '0000-00-00',
  `f_com_tax_place` varchar(50) DEFAULT NULL,
  `m_com_tax_nr` varchar(15) DEFAULT NULL,
  `m_com_tax_date` date DEFAULT '0000-00-00',
  `m_com_tax_place` varchar(50) DEFAULT NULL,
  `officer_date_sign` date DEFAULT '0000-00-00',
  `officer_place_sign` varchar(50) DEFAULT NULL,
  `officer_title` varchar(50) DEFAULT NULL,
  `officer_name` varchar(50) DEFAULT NULL,
  `officer_address` varchar(125) DEFAULT NULL,
  `attendant_type` varchar(25) DEFAULT NULL,
  `birth_time` time DEFAULT '00:00:00',
  `attendant_name` varchar(100) DEFAULT NULL,
  `attendant_title` varchar(25) DEFAULT NULL,
  `attendant_address` varchar(125) DEFAULT NULL,
  `attendant_date_sign` date DEFAULT '0000-00-00',
  `informant_nr` int(11) DEFAULT NULL,
  `informant_name` varchar(100) DEFAULT NULL,
  `informant_relation` varchar(100) DEFAULT NULL,
  `informant_address` varchar(125) DEFAULT NULL,
  `informant_date_sign` date DEFAULT '0000-00-00',
  `encoder_name` varchar(100) DEFAULT NULL,
  `encoder_title` varchar(25) DEFAULT NULL,
  `encoder_date_sign` date DEFAULT '0000-00-00',
  `is_late_reg` tinyint(1) DEFAULT '0',
  `late_affiant_name` varchar(100) DEFAULT NULL,
  `late_affiant_address` varchar(125) DEFAULT NULL,
  `late_baby_citizenship` varchar(5) DEFAULT NULL,
  `late_reason` text,
  `late_purpose` varchar(200) DEFAULT NULL,
  `late_husband` varchar(200) DEFAULT NULL,
  `late_relationship` varchar(100) DEFAULT NULL,
  `affiant_com_tax_nr` varchar(15) DEFAULT NULL,
  `affiant_com_tax_date` date DEFAULT NULL,
  `affiant_com_tax_place` varchar(50) DEFAULT NULL,
  `late_officer_date_sign` date DEFAULT NULL,
  `late_officer_place_sign` varchar(50) DEFAULT NULL,
  `late_officer_title` varchar(50) DEFAULT NULL,
  `late_officer_name` varchar(50) DEFAULT NULL,
  `late_officer_address` varchar(125) DEFAULT NULL,
  `history` text,
  `modify_id` varchar(50) DEFAULT NULL,
  `modify_dt` datetime DEFAULT NULL,
  `create_id` varchar(50) DEFAULT NULL,
  `create_dt` datetime DEFAULT NULL,
  `non_resident_status` varchar(50) DEFAULT NULL,
  `is_tribalwed` tinyint(1) DEFAULT '0',
  `f_fullname` varchar(200) DEFAULT NULL,
  `is_subject_person` tinyint(1) DEFAULT '0',
  `affiant_com_tax_date2` date DEFAULT NULL,
  `affiant_com_tax_place2` varchar(50) DEFAULT NULL,
  `receiver_name` varchar(100) DEFAULT NULL,
  `receiver_title` varchar(100) DEFAULT NULL,
  `receiver_date_sign` date DEFAULT '0000-00-00',
  PRIMARY KEY (`pid`),
  CONSTRAINT `FK_seg_cert_birth` FOREIGN KEY (`pid`) REFERENCES `care_person` (`pid`) ON UPDATE CASCADE
);
;
DELIMITER ;
;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
