
DROP TABLE IF EXISTS `seg_hospital_info_copy`;
CREATE TABLE `seg_hospital_info_copy` (
  `hosp_type` varchar(10) NOT NULL,
  `hosp_id` varchar(5) NOT NULL,
  `hosp_name` varchar(80) NOT NULL,
  `house_case_dailyrate` double(10,4) NOT NULL DEFAULT '0.0000',
  `addr_no_street` varchar(80) NOT NULL,
  `brgy_nr` int(11) NOT NULL,
  `zip_code` varchar(15) NOT NULL,
  `hosp_addr1` varchar(80) NOT NULL,
  `hosp_addr2` varchar(80) NOT NULL,
  `hosp_agency` varchar(100) NOT NULL,
  `hosp_country` varchar(100) NOT NULL,
  `accom_hrs_cutoff` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `pcf` double(10,4) NOT NULL DEFAULT '0.0000',
  `housecase_pcf` double(10,4) NOT NULL DEFAULT '0.0000',
  `hc_rvuadjustment` double(8,5) NOT NULL DEFAULT '0.00000',
  `default_city` int(11) DEFAULT NULL,
  `authrep` varchar(120) NOT NULL,
  `designation` varchar(80) NOT NULL,
  `pf_defaultrate` float(8,3) NOT NULL DEFAULT '0.000',
  `bed_capacity` int(10) unsigned NOT NULL,
  `tax_acctno` varchar(15) NOT NULL,
  `LIS_protocol_type` varchar(10) DEFAULT NULL,
  `LIS_protocol` varchar(10) DEFAULT NULL,
  `LIS_address` varchar(20) DEFAULT NULL,
  `LIS_address_local` varchar(20) DEFAULT NULL,
  `LIS_port` smallint(3) DEFAULT NULL,
  `LIS_folder_path` varchar(200) DEFAULT NULL,
  `LIS_folder_path_local` varchar(200) DEFAULT NULL,
  `LIS_folder_path_inbox` varchar(200) DEFAULT NULL,
  `LIS_folder_path_pdf` varchar(200) DEFAULT NULL,
  `LIS_service_timeout` smallint(3) DEFAULT NULL,
  `LIS_HL7_extension` varchar(10) DEFAULT NULL,
  `LIS_username` varchar(50) DEFAULT NULL,
  `LIS_password` varchar(50) DEFAULT NULL,
  `connection_type` enum('odbc','hl7') DEFAULT NULL,
  PRIMARY KEY (`hosp_id`)
);
